// Code generated by github.com/gnolang/gno. DO NOT EDIT.

//go:build gno
// +build gno

package main

var Play *play.Play

func Render(path string) string { return "" }

func main() {
	Play = play.NewPlay()
}
