// Code generated by github.com/gnolang/gno. DO NOT EDIT.

//go:build gno
// +build gno

// Package models provides functionality for generic models. This file is for managing ratings
package models

import (
	"fmt"
	"github.com/gnolang/gno/stdlibs/stdshim"
)

// RatingInterface defines the contract for the Rating class.
type RatingInterface interface {
	GetID() uuid.UUID     // Return the Rating ID
	GetUserID() uuid.UUID // Return the User ID of this Rating
	GetPostID() uuid.UUID // Return the Post ID of this Rating
	ThumbsUp()            // Set the rating to a thumbs up
	ThumbsDown()          // Set the rating to a thumbs down
	Display() string
}

// Rating represents a rating of a post with basic properties and methods.
type Rating struct {
	ID      uuid.UUID // The ID of the rating
	UserID  uuid.UUID // The ID of the user who rated the post
	PostID  uuid.UUID // The ID of the post that was rated
	Approve bool      // Whether the rating was a thumbs up or down
}

// GetID returns the ID of a rating.
func (r *Rating) GetID() uuid.UUID {
	return r.ID
}

// GetUserID returns the user ID associated with a rating.
func (r *Rating) GetUserID() uuid.UUID {
	return r.UserID
}

// GetPostID returns the post ID associated with a rating.
func (r *Rating) GetPostID() uuid.UUID {
	return r.PostID
}

// Display returns a formatted string containing the rating's details.
func (r *Rating) Display() string {
	return fmt.Sprintf("ID: %s, UserID: %s, PostID: %s, Score: %v", r.GetID(), r.GetUserID(), r.GetPostID(), r.Approve)
}

// ThumbsUp sets the rating to a thumbs up (true).
func (r *Rating) ThumbsUp() {
	r.Approve = true
}

// ThumbsDown sets the rating to a thumbs down (false).
func (r *Rating) ThumbsDown() {
	r.Approve = false
}

// NewRating creates a new rating with a random ID and the given user and post IDs and thumbs up/down status (true/false) and returns a pointer to it.
func NewRating(userID, contentID uuid.UUID, thumbsUp bool) *Rating {
	return &Rating{
		ID:      uuid.Must(uuid.NewV4()),
		UserID:  userID,
		PostID:  contentID,
		Approve: thumbsUp,
	}
}
